parameters:
  extension.routing.routes: '%env(ext_context:ROUTES_RESOURCE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Psr\Log\LoggerAwareInterface:
      calls:
        - [ setLogger ]

  PleskExt\Demo\Http\:
    resource: '../../plib/library/Http'
    exclude:
      - '../../plib/library/Http/ChainedMiddleware.php'
      - '../../plib/library/Http/Resolver/Controller.php'

  routing_request_context:
    class: '\Symfony\Component\Routing\RequestContext'
    factory: [ '@PleskExt\Demo\Http\Factory\RequestContextFactory', 'create' ]

  Doctrine\Common\Annotations\AnnotationReader:
    class: '\Doctrine\Common\Annotations\AnnotationReader'

  Symfony\Component\HttpKernel\Controller\ControllerResolverInterface:
    class: '\Symfony\Component\HttpKernel\Controller\ContainerControllerResolver'

  Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface:
    class: '\Symfony\Component\HttpKernel\Controller\ArgumentResolver'

  Symfony\Component\Routing\Matcher\RequestMatcherInterface:
    class: '\Symfony\Component\Routing\Matcher\UrlMatcher'
    arguments:
      - '@Symfony\Component\Routing\RouteCollection'
      - '@routing_request_context'

  PleskExt\Demo\Http\Factory\RouteCollectionFactoryInterface: '@PleskExt\Demo\Http\Factory\RouteCollectionFactory'

  Symfony\Component\Routing\RouteCollection:
    factory: [ '@PleskExt\Demo\Http\Factory\RouteCollectionFactoryInterface', 'create' ]
    arguments:
      - '%extension.routing.routes%'

  Symfony\Component\Routing\Matcher\UrlMatcherInterface:
    class: '\Symfony\Component\Routing\Matcher\UrlMatcher'
    arguments:
      - '@Symfony\Component\Routing\RouteCollection'
      - '@routing_request_context'

  PleskExt\Demo\Http\ChainedRequestHandler:
    public: false
    arguments:
      $defaultHandler: '@PleskExt\Demo\Http\Handler\NotFoundRequestHandler'
    calls:
      - [ addMiddleware, [ '@PleskExt\Demo\Http\Middleware\ErrorCatcher' ] ]
      - [ addMiddleware, [ '@PleskExt\Demo\Http\Middleware\MatchedController' ] ]

  Psr\Http\Server\RequestHandlerInterface: '@PleskExt\Demo\Http\ChainedRequestHandler'
