imports:
    - { resource: services.yaml }
    - { resource: routing.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    PleskExt\Demo\Test\Stubs\:
        resource: '../../../tests/Stubs/*'
        exclude:
            - '../../../tests/Stubs/Client/*'
            - '../../../tests/Stubs/**/*Builder.php'

    PleskExt\Demo\Test\DI\:
        resource: '../../../tests/DI/*'
        exclude:
            - '../../../tests/DI/ProjectServiceContainerTest.php'

    Psr\Container: '@PleskExt\Demo\Test\DI\Container'


    PleskExt\Demo\Wrapper\Plesk\Settings\SettingsInterface: '@PleskExt\Demo\Test\Stubs\Wrapper\Plesk\Settings\StubSettingsWrapper'

    PleskExt\Demo\Wrapper\Plesk\Crypt\CryptInterface: '@PleskExt\Demo\Test\Stubs\Wrapper\Plesk\Crypt\StubCryptWrapper'

    Psr\Log\LoggerInterface: '@PleskExt\Demo\Test\Stubs\Wrapper\Plesk\Log\StubLoggerWrapper'

    PleskExt\Demo\Wrapper\Plesk\Locale\LocaleInterface: '@PleskExt\Demo\Test\Stubs\Wrapper\Plesk\Locale\StubLocaleWrapper'