imports:
  - { resource: routing.yaml }
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Symfony\Component\DependencyInjection\EnvVarProcessorInterface:
      tags: [ container.env_var_processor ]

  PleskExt\Demo\:
    resource: '../../plib/library/*'
    exclude:
      - '../../plib/library/EventListener.php'
      - '../../plib/library/Http/**/*.php'
      - '../../plib/library/**/*Exception.php'
      - '../../plib/library/**/*Dto.php'
      - '../../plib/library/**/*Event.php'
      - '../../plib/library/Entity'
      - '../../plib/library/UseCases/Command/*/Command.php'
      - '../../plib/library/Wrapper/Plesk/Domain/Plesk*.php'
      - '../../plib/library/Wrapper/Symfony/Validator/Constraints/NotBlank.php'
      - '../../plib/library/Wrapper/Symfony/Validator/Constraints/TrueApiToken.php'
      - '../../plib/library/Wrapper/Symfony/Validator/Constraints/Type.php'
      - '../../plib/library/UseCases/**/*Query.php'
      - '../../plib/library/UseCases/**/ResponseModel.php'

  Symfony\Component\Validator\Validator\ValidatorInterface:
    factory: [ 'PleskExt\Demo\Wrapper\Symfony\Validator\ValidatorFactory', 'createValidator' ]

  Symfony\Component\HttpFoundation\Request:
    class: '\Symfony\Component\HttpFoundation\Request'

  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    class: '\Symfony\Component\Serializer\Normalizer\ObjectNormalizer'

  Symfony\Component\Serializer\Encoder\JsonEncoder:
    class: '\Symfony\Component\Serializer\Encoder\JsonEncoder'

  PleskExt\Demo\Wrapper\Symfony\Serializer\SymfonySerializerFactory:
    arguments:
      - '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
      - '@Symfony\Component\Serializer\Encoder\JsonEncoder'

  Symfony\Component\Validator\ConstraintValidatorFactoryInterface:
    class: '\Symfony\Component\Validator\ContainerConstraintValidatorFactory'
